# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OFDSDedupToolDialog(object):
    def setupUi(self, OFDSDedupToolDialog):
        OFDSDedupToolDialog.setObjectName("OFDSDedupToolDialog")
        OFDSDedupToolDialog.resize(950, 591)
        OFDSDedupToolDialog.setSizeGripEnabled(False)
        self.buttons = QtWidgets.QDialogButtonBox(OFDSDedupToolDialog)
        self.buttons.setGeometry(QtCore.QRect(220, 340, 341, 32))
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.canvas_left = gui.QgsMapCanvas(OFDSDedupToolDialog)
        self.canvas_left.setGeometry(QtCore.QRect(10, 10, 451, 281))
        self.canvas_left.setObjectName("canvas_left")
        self.canvas_right = gui.QgsMapCanvas(OFDSDedupToolDialog)
        self.canvas_right.setGeometry(QtCore.QRect(490, 10, 441, 281))
        self.canvas_right.setObjectName("canvas_right")
        self.canvas_left.raise_()
        self.buttons.raise_()
        self.canvas_right.raise_()

        self.retranslateUi(OFDSDedupToolDialog)
        self.buttons.accepted.connect(OFDSDedupToolDialog.accept) # type: ignore
        self.buttons.rejected.connect(OFDSDedupToolDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OFDSDedupToolDialog)

    def retranslateUi(self, OFDSDedupToolDialog):
        _translate = QtCore.QCoreApplication.translate
        OFDSDedupToolDialog.setWindowTitle(_translate("OFDSDedupToolDialog", "OFDS Dedup Tool"))
from qgis import gui
