# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StyleOFDSDialog(object):
    def setupUi(self, StyleOFDSDialog):
        StyleOFDSDialog.setObjectName("StyleOFDSDialog")
        StyleOFDSDialog.resize(457, 161)
        self.gridLayout_2 = QtWidgets.QGridLayout(StyleOFDSDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spansComboBox = QtWidgets.QComboBox(StyleOFDSDialog)
        self.spansComboBox.setObjectName("spansComboBox")
        self.gridLayout.addWidget(self.spansComboBox, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(StyleOFDSDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 2, 1, 1)
        self.nodesLabel = QtWidgets.QLabel(StyleOFDSDialog)
        self.nodesLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nodesLabel.setObjectName("nodesLabel")
        self.gridLayout.addWidget(self.nodesLabel, 2, 0, 1, 1)
        self.nodesComboBox = QtWidgets.QComboBox(StyleOFDSDialog)
        self.nodesComboBox.setObjectName("nodesComboBox")
        self.gridLayout.addWidget(self.nodesComboBox, 2, 1, 1, 1)
        self.closeButton = QtWidgets.QPushButton(StyleOFDSDialog)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 7, 2, 1, 1)
        self.spansApplyButton = QtWidgets.QPushButton(StyleOFDSDialog)
        self.spansApplyButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spansApplyButton.setObjectName("spansApplyButton")
        self.gridLayout.addWidget(self.spansApplyButton, 3, 2, 1, 1)
        self.infoLabel = QtWidgets.QLabel(StyleOFDSDialog)
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout.addWidget(self.infoLabel, 0, 0, 1, 3)
        self.nodesApplyButton = QtWidgets.QPushButton(StyleOFDSDialog)
        self.nodesApplyButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nodesApplyButton.setObjectName("nodesApplyButton")
        self.gridLayout.addWidget(self.nodesApplyButton, 2, 2, 1, 1)
        self.spansLabel = QtWidgets.QLabel(StyleOFDSDialog)
        self.spansLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spansLabel.setObjectName("spansLabel")
        self.gridLayout.addWidget(self.spansLabel, 3, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(StyleOFDSDialog)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout.addWidget(self.refreshButton, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(StyleOFDSDialog)
        self.closeButton.pressed.connect(StyleOFDSDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StyleOFDSDialog)

    def retranslateUi(self, StyleOFDSDialog):
        _translate = QtCore.QCoreApplication.translate
        StyleOFDSDialog.setWindowTitle(_translate("StyleOFDSDialog", "Style OFDS"))
        self.nodesLabel.setText(_translate("StyleOFDSDialog", "Nodes Layer"))
        self.closeButton.setText(_translate("StyleOFDSDialog", "Close"))
        self.spansApplyButton.setText(_translate("StyleOFDSDialog", "Apply"))
        self.infoLabel.setText(_translate("StyleOFDSDialog", "Apply styles to OFDS layers"))
        self.nodesApplyButton.setText(_translate("StyleOFDSDialog", "Apply"))
        self.spansLabel.setText(_translate("StyleOFDSDialog", "Spans Layer"))
        self.refreshButton.setText(_translate("StyleOFDSDialog", "Refresh Layers"))
