name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-24.04
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.8.2
      with:
        # Note: This token expires July 2025
        # See: https://python-semantic-release.readthedocs.io/en/latest/index.html#index-creating-vcs-releases
        github_token: ${{ secrets.GH_TOKEN_FOR_SEMANTIC_CI_RELEASE }}